os:
  - linux
language: 
  - python
python:
  - "3.3"
  - "3.4"
  - "nightly"
install:
  - pip3 install pytest
  - pip3 install pytest-pep8
  - pip3 install pytest-cov
  - pip3 install python-coveralls
script:
  - py.test my_test.py --cov
after_success:
  - coveralls
